import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Loading from "../components/Template/Loding";

export default function Home() {
  return (
    <>
      <Head>
        <title>옷이 이쁘달</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      홈
    </>
  );
}
